name: 'platform-release-tools-actions'
description: 'aws credentials'
inputs:
  aws-access-key-id:
    description: aws-access-key-id
    required: true
  aws-secret-access-key:
    description: aws-secret-access-key
    required: true


runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-gov-west-1
