name: Configure BigQuery
description: Get BigQuery Service Credentials

runs:
  using: composite
  steps:
    - name: Checkout Testing Tools Team Dashboard Data repo
      uses: actions/checkout@v3
      with:
        repository: department-of-veterans-affairs/qa-standards-dashboard-data
        token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
        path: qa-standards-dashboard-data

    - name: Get BigQuery service credentials
      uses: department-of-veterans-affairs/action-inject-ssm-secrets@latest
      with:
        ssm_parameter: /dsva-vagov/testing-team/bigquery_service_credentials
        env_variable_name: BIGQUERY_SERVICE_CREDENTIALS

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.2
      with:
        project_id: vsp-analytics-and-insights
        service_account_key: ${{ env.BIGQUERY_SERVICE_CREDENTIALS }}
        export_default_credentials: true
